### ISSUE TITLE
Issue following parnotes update to rev. 2

### ISSUE THREAD

**Issue by kevinrue** [chelh/LaTeX-parnotes#1]
Dear Chelsea,

First of all, thank you for taking care of _parnotes_.
Following your recent release of [Parnotes rev. 2](https://www.ctan.org/pkg/parnotes), an issue has appeared in the Bioconductor LATEX Style 2.0 defined in the [BiocStyle package](https://github.com/Bioconductor/BiocStyle) which uses it to produce vignettes for R packages. I have contacted the maintainer of the Bioconductor LATEX Style 2.0 at this [thread](https://github.com/Bioconductor/BiocStyle/issues/7#event-752906446), and we are currently both unable to identify the source of the issue.

I have been developing for the past few months a vignette using that uses Bioconductor LATEX Style 2.0, and recently started using Travis CI for quality checking of my code. You can see how the introduction of parnotes rev. 2 caused the subsequent [builds](https://travis-ci.org/kevinrue/TVTB/builds/148866940) to fail (see the last few lines of this log file for the parnotes error).

I am aware that the link to Travis CI above does not provide you all the files that would help you investigate the issue. The code of my R package is available [here](https://github.com/kevinrue/TVTB) if it helps you. Please do let me know any further information that you may need to help me investigate the issue.

Many thanks in advance for your help,
Kevin

**Comment by chelh** [comment]
I haven't had a chance to try building your whole document yet, but based just on the error message you're getting, please try [this new `parnotes.sty`](https://github.com/chelh/LaTeX-parnotes/files/418739/parnotes.zip)

**Comment by kevinrue** [comment]
Hi Chelsea,

Thank you for the lighting-fast answer!
After making a backup of my /usr/local/texlive/2016/texmf-dist/tex/latex/parnotes/parnotes.sty
I replaced it by the one you linked, and I am glad to report that it works! Everything checks and builds properly again :)

I look forward to the future release! 
Many thanks again,
Kevin
